### ISSUE TITLE
data in meta training and Output dimensionality

### ISSUE THREAD

**Issue by nshervt** [jlindsey15/FeedbackAndLocalPlasticity#1]
Hello,

In [MetaLearningClassification class](https://github.com/jlindsey15/FeedbackAndLocalPlasticity/blob/2f2df41fa04a3aae6bbb953979f8a57237823834/model/oja_meta_learner.py#L206), is {x_traj[0:K], y_traj[0:K]} the training data and {x_rand[0]}  the test input for the meta learning phase? I was not sure what the names "traj" and "rand" stand for here. Also, is there any reason why your example, x_rand[0] includes 5 instances of 5 characters in order (meaning x_rand[0, :5] is 5 instances of the same character, then x_rand[0, 5:10] is for the next character, and so on) but x_traj[k] contains randomly selected instances of these characters?

I also was wondering why the [output dimension of the model is 1000](https://github.com/jlindsey15/FeedbackAndLocalPlasticity/blob/2f2df41fa04a3aae6bbb953979f8a57237823834/model/modelfactory.py#L211)? I was expecting that to be the same as the number of the classes in Omniglot dataset, i.e. [963](https://github.com/jlindsey15/FeedbackAndLocalPlasticity/blob/2f2df41fa04a3aae6bbb953979f8a57237823834/run_training_classification.py#L31).

Thanks!

**Comment by jlindsey15** [comment]
Hi!

-- These variables are poorly named for legacy reasons, but yes you got it right -- x_traj and y_traj are the inner loop training data and x_rand + y_rand are the inner loop test data used to compute the meta-loss

-- Since x_rand is used to compute the meta-loss, the order of the data points in it doesn't matter.  They could be scrambled, but happen to be grouped by class in this implementation.  The order of x_traj does matter.  The example script I provided has the --iid flag set, which scrambles the order of the inner-loop training data (x_traj) to model i.i.d. training.  If the iid flag is not set, the data from each class should appear consecutively (5 from class 1, then 5 from class 2, and so on). 

-- The extra dimensions in the output are not used (in fact, only the first k are used in a k-shot learning problem)

**Comment by nshervt** [comment]
Thanks!
